#!/bin/bash
# install and upgrade node

curl --silent --location https://rpm.nodesource.com/setup | sudo sh
sudo -y yum install nodejs
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
. ~/.nvm/nvm.sh
nvm install stable