#!/bin/bash
# My first script

# install from bower
# link with bower

curl -u 'mpduffey' https://api.github.com/user/repos -d '{"name": "'$1'"}'
cd /home/dev/modules
git clone https://github.com/mpduffey/$1
cd $1
yo ng-mod
git add .
git commit -m 'v0.0.0'
git push origin master
bower link
cd /home/ng-master
bower install mpduffey/$1 --save
bower link $1
echo "$1 linked!"