#!/bin/bash
# Create Angular 2 module

curl -u 'mpduffey' https://api.github.com/user/repos -d '{"name": "'$1'"}'
cd /home/dev/ng2-modules
git clone https://github.com/mpduffey/$1
cd $1
#yo ng2-mod
#git add .
#git commit -m 'v0.0.0'
#git push origin master
bower link
cd /home/ng2-master-app
bower install mpduffey/$1 --save
bower link $1
echo "$1 linked!"